### ISSUE TITLE
Supplying no options or an empty object results in a broken curl String

### ISSUE THREAD

**Issue by leoek** [leoek/fetch-to-curl#15]
## empty options

**Example**
`curl: fetchToCurl("google.com", {})`
**Current**
`curl "google.com"undefined`
**Expected**
`curl "google.com"`

## no options

**Example**
`curl: fetchToCurl("google.com")`
**Current**
fails with the error `cannot read property body of undefined`
**Expected**
`curl "google.com"`

**Comment by thisgeek** [comment]
@leoek I can take this on if you'd like.

**Comment by leoek** [comment]
Sure! I am very busy at the moment, hence the issue instead of a fix 🙈

**Comment by leoek** [comment]
Would be great if you could add a test as well. This case is currently not covered and therefore missed in the initial release.
