### ISSUE TITLE
generateBody problem.

### ISSUE THREAD

**Issue by YoungProducer** [leoek/fetch-to-curl#25]
Hello, I think this function should be like on this attached screenshot 
![image](https://user-images.githubusercontent.com/37039996/103150078-f8c15700-4778-11eb-928f-a1319b408d04.png).
The problem is that generated body doesn't have quotes around braces, in this case curl string will be like this

curl "http://localhost:3000/auth/signin" -X POST -H "host: localhost:3000" -H "user-agent: insomnia/2020.5.2" -H "content-type: application/json" -H "accept: */*" --data-binary {"email":"someemail@gmail.com","password":"mypassword"}

If you will pass this string to cmd, you will get the following error:
{"statusCode":400,"message":"Unexpected token e in JSON at position 0","error":"Bad Request"}curl: (3) URL using bad/illegal format or missing URL

I use this package with nest.js to generate curl string to add ability to execute needed request.

Of course, I may not understand something, if it's true take my apologies, and sorry for my english.

**Comment by leoek** [comment]
Hi @YoungProducer you are right, I just tested this in the playground... Thanks for reporting!

**Comment by leoek** [comment]
@YoungProducer Just published version 0.5.1 which should fix that issue :tada: Can you confirm that it works as you would expect with version 0.5.1?

**Comment by YoungProducer** [comment]
@leoek Hi. Let me a few days to test it. Thanks!

**Comment by leoek** [comment]
@YoungProducer I am closing this. There were no issues when I used it any more and tests are passing too. Feel free to comment if you encounter any issues.
