### ISSUE TITLE
Missing single quote escaping

### ISSUE THREAD

**Issue by electerious** [leoek/fetch-to-curl#42]
My fetch request has body with a JSON that contains single quotes:

```
{"example":"Example with 'single quotes'"}
```

This turns into a `curl` like this:

```
curl 'http://localhost:8090/v1/api' -X POST -H "Content-Type: application/json" --data-binary '{"example":"Example with 'single quotes'"}
```

The single quotes however need to be escaped, because the data-binary is already wrapped in single quotes. The correct way to do so is with `'\''`.

```
curl 'http://localhost:8090/v1/previews/dataSets' -X POST -H "Content-Type: application/json" --data-binary '{"example":"Example with '\''single quotes'\''"}
```

More details: https://stackoverflow.com/a/61891335

---

Thanks a lot for this great module! It makes debugging in our project so much easier.

**Comment by leoek** [comment]
fixed by #45

**Comment by electerious** [comment]
Thanks @leoek! Can you release a new version that contains the fix?

**Comment by leoek** [comment]
Hi @electerious sorry for the late release but it is now live: [0.6.0](https://github.com/leoek/fetch-to-curl/releases/tag/0.6.0)
